[versions]

[libraries]
# local
design = { module = 'com.github.k4dima.testio:design', version = '0.1.0-SNAPSHOT' }

[plugins]
testioApplication = { id = 'testio.app', version = '0.1.0-SNAPSHOT' }
kotlinSerialization = { id = 'org.jetbrains.kotlin.plugin.serialization', version = '2.1.0' }